version: '3.7'
services:
    # https://hub.docker.com/_/postgres
    postgres:
        container_name: sparkify-pgsql
        image: postgres
        environment:
            - POSTGRES_DB=studentdb
            - POSTGRES_USER=student
            - POSTGRES_PASSWORD=student
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - 5432:5432
        volumes:
            - ./initdb/postgres:/docker-entrypoint-initdb.d
            # - ~/docker-data/postgres:/var/lib/postgresql/data
        networks:
          - sparkify

    adminer:
        container_name: sparkify-adminer
        image: adminer
        restart: always
        ports:
          - 8090:8080
        networks:
          - sparkify

    etl:
        container_name: sparkify-etl
        # command that build de airflow image
        build:
            # context past to docker (what folder will be used to take files for build image)
            context: ..
            # dockerfile path
            dockerfile: docker/Dockerfile
        volumes:
            - ../runtime/data:/usr/src/app/data
            - ../runtime:/usr/src/app/
        command: [ "-a", "runjob"] # runjob_and_inspect
        depends_on:
            - postgres
        networks:
          - sparkify

# https://docs.docker.com/compose/networking/
networks:
  sparkify:
