import os
import configparser

# CONFIG
config = configparser.ConfigParser()
config.read(os.path.join(os.path.dirname(__file__), "dl.cfg"))

# source s3
S3_SOURCE = config["S3_SOURCE"]
S3_SOURCE_REGION = S3_SOURCE["REGION"]
LOG_DATA = S3_SOURCE["LOG_DATA"]
SONG_DATA = S3_SOURCE["SONG_DATA"]
LOG_JSONPATH = S3_SOURCE["LOG_JSONPATH"]

# destination s3
S3_DESTINATION = config["S3_DESTINATION"]
# S3_DESTINATION_LOG_DATA = S3_DESTINATION["LOG_DATA"]
# S3_DESTINATION_SONG_DATA = S3_DESTINATION["SONG_DATA"]
S3_DESTINATION_REGION = S3_DESTINATION["REGION"]
S3_DESTINATION_AWS_ACCESS_KEY_ID = S3_DESTINATION["AWS_ACCESS_KEY_ID"]
S3_DESTINATION_AWS_SECRET_ACCESS_KEY = S3_DESTINATION["AWS_SECRET_ACCESS_KEY"]
LAKE_DIM_SONG = S3_DESTINATION["LAKE_DIM_SONG"]